
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyqropcdodsyzkprbznu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5cXJvcGNkb2RzeXprcHJiem51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTgxNDcsImV4cCI6MjA2NTM5NDE0N30.-7CujJlYY6Gg15pNklo_IHR01FgOlI0_UW0vJ2gy7Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
